include:
  - compose-main.yml

services:
  # === INFRA ===
  eureka:
    build: ./eureka
    ports:
      - "8761:8761"
    networks:
      - isys3461_net

  api-gateway:
    build: ./api_gateway
    depends_on:
      - eureka
    ports:
      - "8080:8080"
    networks:
      - isys3461_net
    env_file: .env

  kafka-1:
    image: apache/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka-1:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_RETENTION_HOURS: 24
    networks:
      - isys3461_net

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8888:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: "kraft-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9094
    depends_on:
      - kafka-1
    networks:
      - isys3461_net

  redis:
    image: redis:8.4.0
    ports:
      - "6379:6379"
    networks:
      - isys3461_net

  redis-ui:
    image: redis/redisinsight:2.70
    depends_on:
      - redis
    ports:
      - "5540:5540"
    networks:
      - isys3461_net
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379

networks:
  isys3461_net:
    driver: bridge
